spin_manifest_version = "1"
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""
name = "blog-recommendation"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "blog-recommendation"
source = "target/blog-recommendation.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
sqlite_databases = ["default"]
allowed_http_hosts = ["https://www.fermyon.com/"]
ai_models = ["all-minilm-l6-v2"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
