spin_manifest_version = "1"
authors = ["tpmccallum <tim.mccallum@fermyon.com>"]
description = "An application that can write haiku poetry via Fermyon Serverless AI"
name = "haiku-generator-ts"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "haiku-generator-ts"
source = "target/haiku-generator-ts.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
