spin_manifest_version = "1"
authors = ["Matt Butcher <matt.butcher@fermyon.com>"]
description = ""
name = "silly-walk"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "silly-walk"
source = "target/silly-walk.wasm"
exclude_files = ["**/node_modules"]
ai_models = ["llama2-chat"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
